version: "3.4"

services:
  app:
    image: ogrine-rates_client
    build:
      context: .
      args:
        VITE_OGRINE_API_URL: "https://ogrine.dofus.skkay.fr/api"
    container_name: ogrine-rates_client
    restart: always
    ports:
      - 3000:80
